# Generated by Django 5.1.3 on 2025-07-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionFourierSeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a0', models.FloatField()),
                ('a1', models.FloatField()),
                ('a2', models.FloatField()),
                ('a3', models.FloatField()),
                ('a4', models.FloatField()),
                ('b1', models.FloatField()),
                ('b2', models.FloatField()),
                ('b3', models.FloatField()),
                ('b4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FunctionsTaylorSeriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c0', models.FloatField()),
                ('c1', models.FloatField()),
                ('c2', models.FloatField()),
                ('c3', models.FloatField()),
                ('c4', models.FloatField()),
                ('c5', models.FloatField()),
                ('c6', models.FloatField()),
                ('c7', models.FloatField()),
                ('c8', models.FloatField()),
            ],
        ),
    ]
