# Generated by Django 5.1.3 on 2025-07-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionfourierseriesmodel',
            name='l',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
