# Generated by Django 5.1.3 on 2025-07-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_functions', '0002_functionfourierseriesmodel_l'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionfourierseriesmodel',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='functionfourierseriesmodel',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='functionstaylorseriesmodel',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='functionstaylorseriesmodel',
            name='name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='functionstaylorseriesmodel',
            name='x0',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
