# Generated by Django 5.1.3 on 2025-05-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
