# Generated by Django 5.1.3 on 2025-06-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zero', '0002_zeroimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroStringModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
            ],
        ),
    ]
