# Generated by Django 5.1.3 on 2025-06-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zero', '0003_zerostringmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroCSVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ZeroNameNumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('num', models.FloatField()),
            ],
        ),
    ]
