# Generated by Django 5.1.3 on 2025-07-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zero', '0004_zerocsvmodel_zeronamenummodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroJSONModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
